version: '3'
services:
    ms-sql-server:
        image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
        environment: 
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "Password123"
            MSSQL_PID: Express
        ports:
            - "1433:1433"

    rabbitmq:
        hostname: rabbitmq
        image: rabbitmq:3-management
        container_name: rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        ports:
            - 5672:5672
            - 15672:15672
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:15672"]
            interval: 30s
            timeout: 10s
            retries: 5

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        ports:
            - 27017:27017

    mongo-express:
        image: mongo-express
        restart: always
        ports:
             - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
        depends_on: 
            - mongo

    goleador-web-api:
        environment: 
        - ASPNETCORE_ENVIRONMENT=Docker
        build: .
        ports: 
            - "8080:80"
        depends_on:
            - rabbitmq
            - ms-sql-server
            - mongo
        links: 
            - rabbitmq
        restart: on-failure
        
