version: '3'
services:
    ms-sql-server:
        image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
        environment: 
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "Password123"
            MSSQL_PID: Express
        ports:
            - "1433:1433"
        volumes:
            - C:/sqlVolume/var/opt/mssql/data mcr.microsoft.com/mssql/server

    rabbitmq:
        hostname: rabbitmq
        image: rabbitmq:3-management
        container_name: rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        ports:
            - 5672:5672
            - 15672:15672
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:15672"]
            interval: 30s
            timeout: 10s
            retries: 5

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        ports:
            - 27017:27017
        volumes: 
            - ~/mongo/data:/data/db

    mongo-express:
        image: mongo-express
        restart: always
        ports:
             - 8083:8083
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
        depends_on: 
            - mongo
    
    redis:
        image: "redis:alpine"
        command: redis-server --requirepass sOmE_sEcUrE_pAsS
        ports:
        - "6379:6379"
        volumes:
        - $PWD/redis-data:/var/lib/redis
        - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
        environment:
        - REDIS_REPLICATION_MODE=master

    goleador-web-api:
        environment: 
        - ASPNETCORE_ENVIRONMENT=Docker
        build: .
        ports: 
            - "8080:80"
        depends_on:
            - rabbitmq
            - ms-sql-server
            - mongo
        links: 
            - rabbitmq
        restart: on-failure

    goleador-ui:
        build: ./Goleador.UI/Goleador
        ports: 
            - 4200:80
        depends_on: 
            - goleador-web-api
        
