//@hostName = http://localhost:8080
@hostName = http://localhost:59040
@bookId = 3c39e8a8-6fbf-47dd-9fa4-08d855ad576c

@bookApiKey = AIzaSyAisGZqCY5mXmgrD0avUdhRACHPLhd_G7I

@bookApiUrl = https://www.googleapis.com/books/v1/


POST {{hostName}}/api/book HTTP/1.1
Content-Type: application/json

{
    "name": "test2",
    "author": "test2"
}

GET {{hostName}}/api/book HTTP/1.1

GET {{hostName}}/api/book/{{bookId}} HTTP/1.1

POST {{hostName}}/api/book/{{bookId}}/pomodoros HTTP/1.1
Content-Type: application/json

{
}

PUT {{hostName}}/api/book/startReading/{{bookId}} HTTP/1.1
Content-Type: application/json

{
}

GET {{bookApiUrl}}volumes?q=flowers+inauthor:keyes&key={{bookApiKey}}

GET {{bookApiUrl}}volumes?q=ddd&key={{bookApiKey}}