//@hostName = http://localhost:8080
@hostName = http://localhost:59040
@bookId = 7c724210-70af-46a9-3176-08d84e9caae4

POST {{hostName}}/api/book HTTP/1.1
Content-Type: application/json

{
    "name": "test3",
    "author": "test3"
}

GET {{hostName}}/api/book HTTP/1.1

GET {{hostName}}/api/book/{{bookId}} HTTP/1.1

POST {{hostName}}/api/book/{{bookId}}/pomodoros HTTP/1.1
Content-Type: application/json

{
}

PUT {{hostName}}/api/book/startReading/{{bookId}} HTTP/1.1
Content-Type: application/json

{
}