apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose.exe convert --out ./kubernetes
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: goleador-ui
  name: goleador-ui
spec:
  ports:
  - name: "4200"
    port: 4200
    targetPort: 80
  selector:
    io.kompose.service: goleador-ui
status:
  loadBalancer: {}
